---
title: "web_map"
author: "Areeba Ghumman"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(sf)
library(readxl)
require(tidyverse); require(magrittr);
require(sp); require(sf); require(rgdal);
require(classInt); require(RColorBrewer);
require(ggplot2); require(ggmap); require(leaflet);
require(ggrepel); require(ggsn);
library(ggpubr); library(devtools); library(patchwork); library(htmltools)
library(prettymapr)
require(htmlwidgets); require(mapview)

layer <- st_read("/Users/areeba/Desktop/THISWORKS/THISWORKS.shp")
layer <- st_transform(layer, 4326)

subway_lines <- st_read("/Users/areeba/Desktop/MTA Subway Service Lines_20260425/geo_export_d73419c7-7b70-488a-a6be-526c096dc541.shp")
subway_lines <- st_transform(subway_lines, 4326)

stations <- read_excel("/Users/areeba/Downloads/subway.xlsx")

stations$radius_scaled <- scales::rescale(stations$PERCENTAGE, to = c(3, 15))

tract_lab <- paste0("Neighborhood: ", layer$ntaname)

point_lab <- paste0(
  "Station: ", stations$Stop_Name, "<br>",
  "Line: ", stations$Daytime_Routes, "<br>",
  "Fare Evasion %: ", round(stations$PERCENTAGE * 100, 4), "%"
)

point_popup <- paste0(
  "<strong>Station: </strong>", stations$Stop_Name, "<br/>",
  "<strong>Line: </strong>", stations$Daytime_Routes, "<br/>",
  "<strong>Borough: </strong>", stations$Borough, "<br/>",
  "<strong>Fare Evasion %: </strong>", round(stations$PERCENTAGE * 100, 4), "%<br/>",
  "<strong>Total Crimes: </strong>", stations$total, "<br/>",
  "<strong>Total Riders: </strong>", format(stations$sum_ridership, big.mark = ","), "<br/>"
)

fare_evasion <- leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addPolygons(
    data = layer,
    fillColor = "lightblue",
    color = "gray40",
    weight = 0.5,
    fillOpacity = 0.4,
    label = lapply(tract_lab, HTML),
    labelOptions = labelOptions(
      style = list("font-weight" = "normal", padding = "4px 8px"),
      textsize = "13px",
      direction = "auto"
    ),
    highlightOptions = highlightOptions(
      weight = 2,
      color = "white",
      fillOpacity = 0.6,
      bringToFront = FALSE
    )
  ) %>%
  addPolylines(
    data = subway_lines,
    color = "purple",
    weight = 1.5,
    opacity = 0.8,
    highlightOptions = highlightOptions(
      weight = 3,
      color = "mediumpurple",
      bringToFront = FALSE
    )
  ) %>%
  addCircleMarkers(
    data = stations,
    lng = ~GTFS_Longitude,
    lat = ~GTFS_Latitude,
    radius = ~radius_scaled,
    color = "black",
    weight = 1,
    fillColor = "steelblue",
    fillOpacity = 0.9,
    label = lapply(point_lab, HTML),
    popup = lapply(point_popup, HTML),
    labelOptions = labelOptions(
      style = list("font-weight" = "normal", padding = "4px 8px"),
      textsize = "13px",
      direction = "auto"
    ),
    options = pathOptions(pane = "markerPane")
  ) %>%
  addLegend(
    position = "bottomright",
    title = "Fare Evasion %",
    colors = c("steelblue", "steelblue", "steelblue"),
    labels = c("Low", "Medium", "High"),
    opacity = 0.8
  )

htmlwidgets::saveWidget(fare_evasion, "fare_evasion_map.html", selfcontained = TRUE)
fare_evasion
```

